#!/usr/bin/env node
// omg-origin: kit=oh-my-game-kit-unity | repo=The1Studio/oh-my-game-kit-unity | module=unity-architecture | protected=false
'use strict';

/**
 * generate.test.cjs
 * Tests for scripts/generate.cjs (CLI invocation via child_process)
 */

const path = require('path');
const os = require('os');
const fs = require('fs');
const assert = require('assert');
const { execFileSync } = require('child_process');

const GENERATE = path.resolve(__dirname, '../scripts/generate.cjs');
const FIXTURE = path.resolve(__dirname, '../scripts/fixtures/mini-unity-project');

let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    console.log(`  ✓ ${name}`);
    passed++;
  } catch (err) {
    console.error(`  ✗ ${name}`);
    console.error(`    ${err.message}`);
    failed++;
  }
}

function runGenerate(args, cwd) {
  return execFileSync('node', [GENERATE, ...args], {
    cwd: cwd || FIXTURE,
    windowsHide: true,
    timeout: 30_000,
    stdio: ['pipe', 'pipe', 'ignore']
  }).toString();
}

console.log('\ngenerate.test.cjs');

test('on-demand mode (no args) emits Mermaid assembly graph to stdout', () => {
  const output = runGenerate([]);
  assert.ok(output.includes('graph LR'), `Expected graph LR: ${output.slice(0, 200)}`);
  assert.ok(output.includes('mermaid'), `Expected mermaid code block: ${output.slice(0, 200)}`);
});

test('--type modules --out-dir produces modules.md', () => {
  const outDir = fs.mkdtempSync(path.join(os.tmpdir(), 'omg-test-modules-'));
  try {
    const json = runGenerate(['--type', 'modules', '--out-dir', outDir]);
    const result = JSON.parse(json);
    assert.strictEqual(result.file, 'modules.md');
    assert.ok(fs.existsSync(path.join(outDir, 'modules.md')));
    const content = fs.readFileSync(path.join(outDir, 'modules.md'), 'utf8');
    assert.ok(content.includes('graph LR'), `modules.md missing graph LR: ${content.slice(0, 200)}`);
    assert.ok(content.includes('AUTOGENERATED'), `Missing banner`);
  } finally {
    fs.rmSync(outDir, { recursive: true, force: true });
  }
});

test('--type packages --out-dir produces packages.md', () => {
  const outDir = fs.mkdtempSync(path.join(os.tmpdir(), 'omg-test-packages-'));
  try {
    const json = runGenerate(['--type', 'packages', '--out-dir', outDir]);
    const result = JSON.parse(json);
    assert.strictEqual(result.file, 'packages.md');
    assert.ok(fs.existsSync(path.join(outDir, 'packages.md')));
    const content = fs.readFileSync(path.join(outDir, 'packages.md'), 'utf8');
    assert.ok(content.includes('graph LR'), `packages.md missing graph: ${content.slice(0, 200)}`);
  } finally {
    fs.rmSync(outDir, { recursive: true, force: true });
  }
});

test('--type c4 --out-dir produces architecture.md', () => {
  const outDir = fs.mkdtempSync(path.join(os.tmpdir(), 'omg-test-c4-'));
  try {
    const json = runGenerate(['--type', 'c4', '--out-dir', outDir]);
    const result = JSON.parse(json);
    assert.strictEqual(result.file, 'architecture.md');
    assert.ok(fs.existsSync(path.join(outDir, 'architecture.md')));
    const content = fs.readFileSync(path.join(outDir, 'architecture.md'), 'utf8');
    assert.ok(content.includes('graph TB'), `architecture.md missing graph TB: ${content.slice(0, 200)}`);
  } finally {
    fs.rmSync(outDir, { recursive: true, force: true });
  }
});

test('stdout JSON result has "file", "warnings", "capabilities_skipped" keys', () => {
  const outDir = fs.mkdtempSync(path.join(os.tmpdir(), 'omg-test-schema-'));
  try {
    const json = runGenerate(['--type', 'modules', '--out-dir', outDir]);
    const result = JSON.parse(json);
    assert.ok('file' in result, 'Missing "file" key');
    assert.ok('warnings' in result, 'Missing "warnings" key');
    assert.ok('capabilities_skipped' in result, 'Missing "capabilities_skipped" key');
    assert.ok(Array.isArray(result.warnings), '"warnings" should be array');
    assert.ok(Array.isArray(result.capabilities_skipped), '"capabilities_skipped" should be array');
  } finally {
    fs.rmSync(outDir, { recursive: true, force: true });
  }
});

test('result.file is relative (not absolute)', () => {
  const outDir = fs.mkdtempSync(path.join(os.tmpdir(), 'omg-test-rel-'));
  try {
    const json = runGenerate(['--type', 'modules', '--out-dir', outDir]);
    const result = JSON.parse(json);
    assert.ok(!path.isAbsolute(result.file), `file should be relative: ${result.file}`);
  } finally {
    fs.rmSync(outDir, { recursive: true, force: true });
  }
});

console.log(`\n  ${passed} passed, ${failed} failed\n`);
if (failed > 0) process.exit(1);
