#!/usr/bin/env node
// omg-origin: kit=oh-my-game-kit-unity | repo=The1Studio/oh-my-game-kit-unity | module=unity-architecture | protected=false
'use strict';

/**
 * generate.cjs
 *
 * Adapter entry point. Implements the OMG adapter contract:
 *
 *   Refresh mode:  node generate.cjs --type <capability> --out-dir <absPath>
 *   On-demand mode: node generate.cjs  (no args — legacy, outputs modules graph to stdout)
 *
 * Stdout (refresh mode): JSON { "file": "<relPath>", "warnings": [...], "capabilities_skipped": [...] }
 * Exit 0 = success, exit 1 = fatal error
 *
 * Capabilities: modules | classes | packages | c4
 */

const fs = require('fs');
const path = require('path');
const os = require('os');

const { parseAsmdefs } = require('./lib/asmdef-parser.cjs');
const { generateClassDiagrams, isCs2mmdAvailable } = require('./lib/cs2mermaid-wrapper.cjs');
const { extractPackages } = require('./lib/packages-extractor.cjs');
const { synthesizeC4 } = require('./lib/c4-synthesizer.cjs');

const OMG_BANNER = '<!-- AUTOGENERATED by omg diagram refresh — DO NOT EDIT. -->\n';

// Parse CLI arguments
const args = process.argv.slice(2);

function getArg(name) {
  const idx = args.indexOf(name);
  return idx !== -1 ? args[idx + 1] : null;
}

const type = getArg('--type');
const outDir = getArg('--out-dir');
const includeGenerated = args.includes('--include-generated');

// On-demand mode (legacy, no args) — emit modules graph to stdout
if (!type && !outDir) {
  const projectRoot = process.cwd();
  const { mermaid, warnings } = parseAsmdefs(projectRoot);
  if (warnings.length > 0) {
    process.stderr.write(warnings.join('\n') + '\n');
  }
  process.stdout.write('```mermaid\n' + mermaid + '\n```\n');
  process.exit(0);
}

// Validate refresh mode args
if (!type) {
  process.stderr.write('Error: --type is required\n');
  process.exit(1);
}
if (!outDir) {
  process.stderr.write('Error: --out-dir is required\n');
  process.exit(1);
}

const VALID_TYPES = ['modules', 'classes', 'packages', 'c4'];
if (!VALID_TYPES.includes(type)) {
  process.stderr.write(`Error: --type must be one of: ${VALID_TYPES.join(', ')}\n`);
  process.exit(1);
}

// Validate outDir is absolute
if (!path.isAbsolute(outDir)) {
  process.stderr.write('Error: --out-dir must be an absolute path\n');
  process.exit(1);
}

// Ensure outDir exists
fs.mkdirSync(outDir, { recursive: true });

const projectRoot = process.cwd();

async function main() {
  try {
    switch (type) {
      case 'modules': return await generateModules();
      case 'classes': return await generateClasses();
      case 'packages': return await generatePackages();
      case 'c4': return await generateC4();
      default:
        process.stderr.write(`Unknown type: ${type}\n`);
        process.exit(1);
    }
  } catch (err) {
    process.stderr.write(`Fatal error in generate.cjs [${type}]: ${err.message}\n${err.stack}\n`);
    process.exit(1);
  }
}

// --- modules ---
async function generateModules() {
  const { mermaid, warnings } = parseAsmdefs(projectRoot);
  const content = `${OMG_BANNER}\n# Assembly Graph\n\n\`\`\`mermaid\n${mermaid}\n\`\`\`\n`;
  const outFile = path.join(outDir, 'modules.md');
  fs.writeFileSync(outFile, content, 'utf8');
  emitResult('modules.md', warnings, []);
}

// --- classes ---
async function generateClasses() {
  const capabilitiesSkipped = [];
  const allWarnings = [];

  if (!isCs2mmdAvailable()) {
    const notice = `${OMG_BANNER}\n# Class Diagrams\n\n> ⚠️ Not available — install via \`omg diagram install cs2mermaid\`\n> Requires .NET 8 SDK: https://dotnet.microsoft.com/download/dotnet/8.0\n`;
    const outFile = path.join(outDir, 'classes.md');
    fs.writeFileSync(outFile, notice, 'utf8');
    emitResult('classes.md', [], ['classes']);
    return;
  }

  const { nodes, edges, warnings: parseWarnings } = parseAsmdefs(projectRoot);
  allWarnings.push(...parseWarnings);

  if (nodes.length === 0) {
    const content = `${OMG_BANNER}\n# Class Diagrams\n\n> No assemblies found in project.\n`;
    fs.writeFileSync(path.join(outDir, 'classes.md'), content, 'utf8');
    emitResult('classes.md', allWarnings, []);
    return;
  }

  // Generate per-asmdef diagrams
  const results = await generateClassDiagrams(nodes, { includeGenerated });

  // Write per-asmdef files
  const indexLines = [`${OMG_BANNER}\n# Class Diagrams\n`];
  let timedOut = 0;
  let failed = 0;

  for (const result of results) {
    const safeName = result.name.replace(/[^a-zA-Z0-9.\-_]/g, '_');
    const fileName = `classes-${safeName}.md`;
    const filePath = path.join(outDir, fileName);

    const content = `${OMG_BANNER}\n# ${result.name}\n\n\`\`\`mermaid\n${result.mermaid}\n\`\`\`\n`;
    fs.writeFileSync(filePath, content, 'utf8');

    indexLines.push(`- [${result.name}](./${fileName})`);
    allWarnings.push(...result.warnings);

    if (result.warnings.some(w => w.includes('timed out'))) timedOut++;
    if (result.warnings.some(w => w.includes('failed') || w.includes('Error'))) failed++;
  }

  // Budget warning: > 15% timed out
  const timeoutRate = nodes.length > 0 ? timedOut / nodes.length : 0;
  if (timeoutRate > 0.15) {
    allWarnings.push(`⚠️ ${timedOut} of ${nodes.length} assemblies (${(timeoutRate * 100).toFixed(0)}%) timed out. Consider reducing assembly size or increasing timeout.`);
  }

  const indexContent = indexLines.join('\n') + '\n';
  fs.writeFileSync(path.join(outDir, 'classes.md'), indexContent, 'utf8');
  emitResult('classes.md', allWarnings, capabilitiesSkipped);
}

// --- packages ---
async function generatePackages() {
  const { mermaid, warnings } = extractPackages(projectRoot);
  const content = `${OMG_BANNER}\n# UPM Package Dependencies\n\n\`\`\`mermaid\n${mermaid}\n\`\`\`\n`;
  const outFile = path.join(outDir, 'packages.md');
  fs.writeFileSync(outFile, content, 'utf8');
  emitResult('packages.md', warnings, []);
}

// --- c4 ---
async function generateC4() {
  const { nodes, edges, warnings: parseWarnings } = parseAsmdefs(projectRoot);
  const { mermaid, warnings: c4Warnings } = synthesizeC4(nodes, edges);
  const allWarnings = [...parseWarnings, ...c4Warnings];
  const content = `${OMG_BANNER}\n# Architecture (C4 View)\n\n\`\`\`mermaid\n${mermaid}\n\`\`\`\n`;
  const outFile = path.join(outDir, 'architecture.md');
  fs.writeFileSync(outFile, content, 'utf8');
  emitResult('architecture.md', allWarnings, []);
}

function emitResult(file, warnings, capabilitiesSkipped) {
  const result = {
    file,
    warnings: warnings.map(String),
    capabilities_skipped: capabilitiesSkipped
  };
  process.stdout.write(JSON.stringify(result) + '\n');
  process.exit(0);
}

main();
