#!/usr/bin/env node
// omg-origin: kit=oh-my-game-kit-cocos | repo=The1Studio/oh-my-game-kit-cocos | module=base | protected=false
'use strict';

/**
 * generate.cjs
 *
 * Cocos adapter entry point. Implements the OMG adapter contract (v1.0.0):
 *   node generate.cjs --type <capability> --out-dir <absPath>
 *
 * Capabilities: classes | modules | scenes | prefabs
 * Stdout: JSON { file, warnings, capabilities_skipped }
 * Exit 0 = success, exit 1 = fatal error
 *
 * MVP scope (v1.0.0): scenes + prefabs via the bundled JSON walker are fully implemented.
 * classes + modules emit a stub with a clear install hint until the ts-morph / dep-cruiser
 * extractors land in a follow-up release.
 */

const fs = require('fs');
const path = require('path');
const sceneWalker = require('./lib/scene-walker.cjs');

const OMG_BANNER = '<!-- AUTOGENERATED by omg diagram refresh — DO NOT EDIT. -->\n';
const SKIP_DIRS = new Set(['node_modules', 'build', 'temp', 'library', 'local', '.git']);
const MAX_DEPTH = 12;

// --- CLI parsing --------------------------------------------------------

function getArg(name) {
  const args = process.argv.slice(2);
  const idx = args.indexOf(name);
  return idx !== -1 ? args[idx + 1] : null;
}

function die(msg, code = 1) {
  process.stderr.write('Error: ' + msg + '\n');
  process.exit(code);
}

function emitResult(file, warnings, capabilitiesSkipped) {
  const result = {
    file,
    warnings: (warnings || []).map(String),
    capabilities_skipped: capabilitiesSkipped || []
  };
  process.stdout.write(JSON.stringify(result) + '\n');
  process.exit(0);
}

// --- asset discovery ----------------------------------------------------

function findAssetsByExt(root, exts) {
  const out = [];
  function walk(dir, depth) {
    if (depth > MAX_DEPTH) return;
    let entries;
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const e of entries) {
      if (SKIP_DIRS.has(e.name.toLowerCase())) continue;
      const full = path.join(dir, e.name);
      if (e.isDirectory()) walk(full, depth + 1);
      else if (e.isFile()) {
        for (const ext of exts) if (e.name.endsWith(ext)) { out.push(full); break; }
      }
    }
  }
  const assets = path.join(root, 'assets');
  if (fs.existsSync(assets)) walk(assets, 0);
  return out;
}

// --- capability generators ----------------------------------------------

function generateScenes(projectRoot, outDir) {
  const files = findAssetsByExt(projectRoot, ['.scene']);
  const warnings = [];
  const sections = [OMG_BANNER, '# Scene Hierarchy', ''];
  if (files.length === 0) {
    sections.push('> No `.scene` files found under `assets/`.');
  } else {
    for (const f of files) {
      const rel = path.relative(projectRoot, f);
      sections.push(`## ${rel}`, '');
      let parsed;
      try {
        parsed = JSON.parse(fs.readFileSync(f, 'utf8'));
      } catch (err) {
        warnings.push(`Failed to parse ${rel}: ${err.message}`);
        sections.push(`> Parse error: ${err.message}`, '');
        continue;
      }
      const { mermaid, nodeCount, truncated } = sceneWalker.walk(parsed, { label: rel });
      if (truncated) warnings.push(`Scene ${rel} truncated at ${nodeCount} nodes`);
      sections.push('```mermaid', mermaid, '```', '');
    }
  }
  const outFile = path.join(outDir, 'scenes.md');
  fs.writeFileSync(outFile, sections.join('\n'), 'utf8');
  emitResult('scenes.md', warnings, []);
}

function generatePrefabs(projectRoot, outDir) {
  const files = findAssetsByExt(projectRoot, ['.prefab']);
  const warnings = [];
  const sections = [OMG_BANNER, '# Prefab Component Trees', ''];
  if (files.length === 0) {
    sections.push('> No `.prefab` files found under `assets/`.');
  } else {
    for (const f of files) {
      const rel = path.relative(projectRoot, f);
      sections.push(`## ${rel}`, '');
      let parsed;
      try {
        parsed = JSON.parse(fs.readFileSync(f, 'utf8'));
      } catch (err) {
        warnings.push(`Failed to parse ${rel}: ${err.message}`);
        sections.push(`> Parse error: ${err.message}`, '');
        continue;
      }
      const { mermaid, nodeCount, truncated } = sceneWalker.walk(parsed, { label: rel });
      if (truncated) warnings.push(`Prefab ${rel} truncated at ${nodeCount} nodes`);
      sections.push('```mermaid', mermaid, '```', '');
    }
  }
  const outFile = path.join(outDir, 'prefabs.md');
  fs.writeFileSync(outFile, sections.join('\n'), 'utf8');
  emitResult('prefabs.md', warnings, []);
}

function generateClassesStub(projectRoot, outDir) {
  const content = OMG_BANNER + '\n' +
    '# Class Diagrams\n\n' +
    '> Not available in `cocos-script-graph@1.0.0` MVP. Install per-project extractor:\n' +
    '> `npm i --save-dev ts-morph` and upgrade the skill to v1.1.0 when released.\n';
  fs.writeFileSync(path.join(outDir, 'classes.md'), content, 'utf8');
  emitResult('classes.md', [], ['classes']);
}

function generateModulesStub(projectRoot, outDir) {
  const content = OMG_BANNER + '\n' +
    '# Module Dependency Graph\n\n' +
    '> Not available in `cocos-script-graph@1.0.0` MVP. Install per-project extractor:\n' +
    '> `npm i --save-dev dependency-cruiser` and upgrade the skill to v1.1.0 when released.\n';
  fs.writeFileSync(path.join(outDir, 'modules.md'), content, 'utf8');
  emitResult('modules.md', [], ['modules']);
}

// --- main ---------------------------------------------------------------

const type = getArg('--type');
const outDir = getArg('--out-dir');

if (!type) die('--type is required');
if (!outDir) die('--out-dir is required');
if (!path.isAbsolute(outDir)) die('--out-dir must be an absolute path');

const VALID = ['classes', 'modules', 'scenes', 'prefabs'];
if (!VALID.includes(type)) die(`--type must be one of: ${VALID.join(', ')}`);

fs.mkdirSync(outDir, { recursive: true });
const projectRoot = process.cwd();

try {
  switch (type) {
    case 'scenes':  return generateScenes(projectRoot, outDir);
    case 'prefabs': return generatePrefabs(projectRoot, outDir);
    case 'classes': return generateClassesStub(projectRoot, outDir);
    case 'modules': return generateModulesStub(projectRoot, outDir);
  }
} catch (err) {
  process.stderr.write(`Fatal error in generate.cjs [${type}]: ${err.message}\n${err.stack}\n`);
  process.exit(1);
}
